### ISSUE TITLE
Hoping add math typo typing feature.

### ISSUE THREAD

**Issue by h0l4ct13** [joway/hugo-theme-yinyang#33]
Hi @joway your theme is excellent and it seems doesn't support math typo like Latex or "tex in markdown", at least in my site
when I add math typo it shows incorrectly as for the picture below ...

So I want to know how to add the feature to support the math typing like add MathJax by myself, and that's will be the best if you can add that in the future.

Thanks. 

![image](https://user-images.githubusercontent.com/45538642/103128803-af69fc80-46d1-11eb-95df-6d3a3edba58c.png)

**Comment by koraylinux** [comment]
It's very easy to integrate KaTex into hugo. I just tested and it works.

Remember the update katex version to **0.12.0** in partials math.html file and remove the markup type since **mmark** is deprecated and will be removed in a future release.

Short Tutorial: https://dawnarc.com/2019/09/hugokatex-intergration/

**Comment by h0l4ct13** [comment]
> It's very easy to integrate KaTex into hugo. I just tested and it works.
> 
> Remember the update katex version to **0.12.0** in partials math.html file and remove the markup type since **mmark** is deprecated and will be removed in a future release.
> 
> Short Tutorial: https://dawnarc.com/2019/09/hugokatex-intergration/

Thank you very much, It really works  well!
